name: Java CI with Maven

on:
  push:
    branches:
      - main
    paths:
      - 'simple-data-backend/**'
    # trigger events for SemVer like tags
    tags:
      - '*.*.*'
      - '*.*.*-*'
  pull_request:
    branches:
      - main
    paths:
      - 'simple-data-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: simple-data-backend/
        run: |
          mvn clean verify --batch-mode
